version: '2'

services:
  # Define a InfluxDB service
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - ./influxdb/env/env.influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    networks:
      - smartplug-network

  # Define a service for using the influx CLI tool.
  # docker-compose -p smartplug run influxdb-cli
  influxdb-cli:
    image: influxdb:latest
    container_name: influxdb-cli
    entrypoint:
      - influx
      - -host
      - influxdb
    depends_on:
      - influxdb
    networks:
      - smartplug-network

  # Define a Chronograf service
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    volumes:
      - ./chronograf/data:/var/lib/chronograf
    ports:
      - "8888:8888"
    command: "chronograf --influxdb-url=http://influxdb:8086"
    depends_on:
      - influxdb
    networks:
      - smartplug-network

  # Define a Grafana service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - ./grafana/env/env.grafana
    depends_on:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - smartplug-network

  # # Define a Telegraf service (demo metrics on docker container CPU and RAM usage, to remove)
  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   depends_on:
  #     - influxdb
  #   volumes:
  #     - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #   networks:
  #     - smartplug-network

networks:
  smartplug-network:
    driver: bridge
