version: '2'

# Basic function options
x-function: &smartplug-function
  image: telegraf-smartplug
  build:
    context: .
    dockerfile: Dockerfile.smartplug
  depends_on:
    - influxdb
  volumes:
    - ./telegraf/conf/telegraf-smartplug.conf:/etc/telegraf/telegraf.conf:ro
  networks:
    - smartplug-network

services:
  telegraf-smartplug-0:
    container_name: telegraf-smartplug-0
    environment:
      STR_DEVICE_NAME: "Room Heater"
      STR_DEVICE_IP: "192.168.1.104"
      STR_DEVICE_MAC: "AC:84:C6:3B:A0:CA"
    <<: *smartplug-function

  telegraf-smartplug-1:
    container_name: telegraf-smartplug-1
    environment:
      STR_DEVICE_NAME: "SevenPlug1"
      STR_DEVICE_IP: "192.168.1.105"
      STR_DEVICE_MAC: "AC:84:C6:89:EA:44"
    <<: *smartplug-function

  telegraf-smartplug-2:
    container_name: telegraf-smartplug-2
    environment:
      STR_DEVICE_NAME: "SevenPlug2"
      STR_DEVICE_IP: "192.168.1.106"
      STR_DEVICE_MAC: "AC:84:C6:59:D2:A3"
    <<: *smartplug-function

networks:
  smartplug-network:
    driver: bridge
