version: '2'

# Basic function options
x-function: &datacolector-function
  image: datacolector
  build:
    context: ./datacolector
    dockerfile: Dockerfile
  restart: always
  depends_on:
    - influxdb
  volumes:
    - ./datacolector/conf/telegraf-smartplug.conf:/etc/telegraf/telegraf.conf:ro
  networks:
    - smartplug-network

services:
# <SERVICES.SMARTPLUG.TMPL>

networks:
  smartplug-network:
    driver: bridge
